// source: v1/cluster.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.teleport.terminal.v1.Cluster', null, global);
goog.exportSymbol('proto.teleport.terminal.v1.ClusterACL', null, global);
goog.exportSymbol('proto.teleport.terminal.v1.ResourceAccess', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.teleport.terminal.v1.Cluster = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.teleport.terminal.v1.Cluster, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.teleport.terminal.v1.Cluster.displayName = 'proto.teleport.terminal.v1.Cluster';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.teleport.terminal.v1.ClusterACL = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.teleport.terminal.v1.ClusterACL.repeatedFields_, null);
};
goog.inherits(proto.teleport.terminal.v1.ClusterACL, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.teleport.terminal.v1.ClusterACL.displayName = 'proto.teleport.terminal.v1.ClusterACL';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.teleport.terminal.v1.ResourceAccess = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.teleport.terminal.v1.ResourceAccess, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.teleport.terminal.v1.ResourceAccess.displayName = 'proto.teleport.terminal.v1.ResourceAccess';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.teleport.terminal.v1.Cluster.prototype.toObject = function(opt_includeInstance) {
  return proto.teleport.terminal.v1.Cluster.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.teleport.terminal.v1.Cluster} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.teleport.terminal.v1.Cluster.toObject = function(includeInstance, msg) {
  var f, obj = {
    uri: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    connected: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    acl: (f = msg.getAcl()) && proto.teleport.terminal.v1.ClusterACL.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.teleport.terminal.v1.Cluster}
 */
proto.teleport.terminal.v1.Cluster.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.teleport.terminal.v1.Cluster;
  return proto.teleport.terminal.v1.Cluster.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.teleport.terminal.v1.Cluster} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.teleport.terminal.v1.Cluster}
 */
proto.teleport.terminal.v1.Cluster.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUri(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setConnected(value);
      break;
    case 4:
      var value = new proto.teleport.terminal.v1.ClusterACL;
      reader.readMessage(value,proto.teleport.terminal.v1.ClusterACL.deserializeBinaryFromReader);
      msg.setAcl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.teleport.terminal.v1.Cluster.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.teleport.terminal.v1.Cluster.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.teleport.terminal.v1.Cluster} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.teleport.terminal.v1.Cluster.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUri();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getConnected();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getAcl();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.teleport.terminal.v1.ClusterACL.serializeBinaryToWriter
    );
  }
};


/**
 * optional string uri = 1;
 * @return {string}
 */
proto.teleport.terminal.v1.Cluster.prototype.getUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.teleport.terminal.v1.Cluster} returns this
 */
proto.teleport.terminal.v1.Cluster.prototype.setUri = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.teleport.terminal.v1.Cluster.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.teleport.terminal.v1.Cluster} returns this
 */
proto.teleport.terminal.v1.Cluster.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bool connected = 3;
 * @return {boolean}
 */
proto.teleport.terminal.v1.Cluster.prototype.getConnected = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.teleport.terminal.v1.Cluster} returns this
 */
proto.teleport.terminal.v1.Cluster.prototype.setConnected = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional ClusterACL acl = 4;
 * @return {?proto.teleport.terminal.v1.ClusterACL}
 */
proto.teleport.terminal.v1.Cluster.prototype.getAcl = function() {
  return /** @type{?proto.teleport.terminal.v1.ClusterACL} */ (
    jspb.Message.getWrapperField(this, proto.teleport.terminal.v1.ClusterACL, 4));
};


/**
 * @param {?proto.teleport.terminal.v1.ClusterACL|undefined} value
 * @return {!proto.teleport.terminal.v1.Cluster} returns this
*/
proto.teleport.terminal.v1.Cluster.prototype.setAcl = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.teleport.terminal.v1.Cluster} returns this
 */
proto.teleport.terminal.v1.Cluster.prototype.clearAcl = function() {
  return this.setAcl(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.teleport.terminal.v1.Cluster.prototype.hasAcl = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.teleport.terminal.v1.ClusterACL.repeatedFields_ = [12];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.teleport.terminal.v1.ClusterACL.prototype.toObject = function(opt_includeInstance) {
  return proto.teleport.terminal.v1.ClusterACL.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.teleport.terminal.v1.ClusterACL} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.teleport.terminal.v1.ClusterACL.toObject = function(includeInstance, msg) {
  var f, obj = {
    sessions: (f = msg.getSessions()) && proto.teleport.terminal.v1.ResourceAccess.toObject(includeInstance, f),
    authConnectors: (f = msg.getAuthConnectors()) && proto.teleport.terminal.v1.ResourceAccess.toObject(includeInstance, f),
    roles: (f = msg.getRoles()) && proto.teleport.terminal.v1.ResourceAccess.toObject(includeInstance, f),
    users: (f = msg.getUsers()) && proto.teleport.terminal.v1.ResourceAccess.toObject(includeInstance, f),
    trustedClusters: (f = msg.getTrustedClusters()) && proto.teleport.terminal.v1.ResourceAccess.toObject(includeInstance, f),
    events: (f = msg.getEvents()) && proto.teleport.terminal.v1.ResourceAccess.toObject(includeInstance, f),
    tokens: (f = msg.getTokens()) && proto.teleport.terminal.v1.ResourceAccess.toObject(includeInstance, f),
    servers: (f = msg.getServers()) && proto.teleport.terminal.v1.ResourceAccess.toObject(includeInstance, f),
    apps: (f = msg.getApps()) && proto.teleport.terminal.v1.ResourceAccess.toObject(includeInstance, f),
    dbs: (f = msg.getDbs()) && proto.teleport.terminal.v1.ResourceAccess.toObject(includeInstance, f),
    kubeservers: (f = msg.getKubeservers()) && proto.teleport.terminal.v1.ResourceAccess.toObject(includeInstance, f),
    sshLoginsList: (f = jspb.Message.getRepeatedField(msg, 12)) == null ? undefined : f,
    accessRequests: (f = msg.getAccessRequests()) && proto.teleport.terminal.v1.ResourceAccess.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.teleport.terminal.v1.ClusterACL}
 */
proto.teleport.terminal.v1.ClusterACL.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.teleport.terminal.v1.ClusterACL;
  return proto.teleport.terminal.v1.ClusterACL.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.teleport.terminal.v1.ClusterACL} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.teleport.terminal.v1.ClusterACL}
 */
proto.teleport.terminal.v1.ClusterACL.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.teleport.terminal.v1.ResourceAccess;
      reader.readMessage(value,proto.teleport.terminal.v1.ResourceAccess.deserializeBinaryFromReader);
      msg.setSessions(value);
      break;
    case 2:
      var value = new proto.teleport.terminal.v1.ResourceAccess;
      reader.readMessage(value,proto.teleport.terminal.v1.ResourceAccess.deserializeBinaryFromReader);
      msg.setAuthConnectors(value);
      break;
    case 3:
      var value = new proto.teleport.terminal.v1.ResourceAccess;
      reader.readMessage(value,proto.teleport.terminal.v1.ResourceAccess.deserializeBinaryFromReader);
      msg.setRoles(value);
      break;
    case 4:
      var value = new proto.teleport.terminal.v1.ResourceAccess;
      reader.readMessage(value,proto.teleport.terminal.v1.ResourceAccess.deserializeBinaryFromReader);
      msg.setUsers(value);
      break;
    case 5:
      var value = new proto.teleport.terminal.v1.ResourceAccess;
      reader.readMessage(value,proto.teleport.terminal.v1.ResourceAccess.deserializeBinaryFromReader);
      msg.setTrustedClusters(value);
      break;
    case 6:
      var value = new proto.teleport.terminal.v1.ResourceAccess;
      reader.readMessage(value,proto.teleport.terminal.v1.ResourceAccess.deserializeBinaryFromReader);
      msg.setEvents(value);
      break;
    case 7:
      var value = new proto.teleport.terminal.v1.ResourceAccess;
      reader.readMessage(value,proto.teleport.terminal.v1.ResourceAccess.deserializeBinaryFromReader);
      msg.setTokens(value);
      break;
    case 8:
      var value = new proto.teleport.terminal.v1.ResourceAccess;
      reader.readMessage(value,proto.teleport.terminal.v1.ResourceAccess.deserializeBinaryFromReader);
      msg.setServers(value);
      break;
    case 9:
      var value = new proto.teleport.terminal.v1.ResourceAccess;
      reader.readMessage(value,proto.teleport.terminal.v1.ResourceAccess.deserializeBinaryFromReader);
      msg.setApps(value);
      break;
    case 10:
      var value = new proto.teleport.terminal.v1.ResourceAccess;
      reader.readMessage(value,proto.teleport.terminal.v1.ResourceAccess.deserializeBinaryFromReader);
      msg.setDbs(value);
      break;
    case 11:
      var value = new proto.teleport.terminal.v1.ResourceAccess;
      reader.readMessage(value,proto.teleport.terminal.v1.ResourceAccess.deserializeBinaryFromReader);
      msg.setKubeservers(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.addSshLogins(value);
      break;
    case 13:
      var value = new proto.teleport.terminal.v1.ResourceAccess;
      reader.readMessage(value,proto.teleport.terminal.v1.ResourceAccess.deserializeBinaryFromReader);
      msg.setAccessRequests(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.teleport.terminal.v1.ClusterACL.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.teleport.terminal.v1.ClusterACL.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.teleport.terminal.v1.ClusterACL} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.teleport.terminal.v1.ClusterACL.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSessions();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.teleport.terminal.v1.ResourceAccess.serializeBinaryToWriter
    );
  }
  f = message.getAuthConnectors();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.teleport.terminal.v1.ResourceAccess.serializeBinaryToWriter
    );
  }
  f = message.getRoles();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.teleport.terminal.v1.ResourceAccess.serializeBinaryToWriter
    );
  }
  f = message.getUsers();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.teleport.terminal.v1.ResourceAccess.serializeBinaryToWriter
    );
  }
  f = message.getTrustedClusters();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.teleport.terminal.v1.ResourceAccess.serializeBinaryToWriter
    );
  }
  f = message.getEvents();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.teleport.terminal.v1.ResourceAccess.serializeBinaryToWriter
    );
  }
  f = message.getTokens();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.teleport.terminal.v1.ResourceAccess.serializeBinaryToWriter
    );
  }
  f = message.getServers();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.teleport.terminal.v1.ResourceAccess.serializeBinaryToWriter
    );
  }
  f = message.getApps();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.teleport.terminal.v1.ResourceAccess.serializeBinaryToWriter
    );
  }
  f = message.getDbs();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.teleport.terminal.v1.ResourceAccess.serializeBinaryToWriter
    );
  }
  f = message.getKubeservers();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.teleport.terminal.v1.ResourceAccess.serializeBinaryToWriter
    );
  }
  f = message.getSshLoginsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      12,
      f
    );
  }
  f = message.getAccessRequests();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      proto.teleport.terminal.v1.ResourceAccess.serializeBinaryToWriter
    );
  }
};


/**
 * optional ResourceAccess sessions = 1;
 * @return {?proto.teleport.terminal.v1.ResourceAccess}
 */
proto.teleport.terminal.v1.ClusterACL.prototype.getSessions = function() {
  return /** @type{?proto.teleport.terminal.v1.ResourceAccess} */ (
    jspb.Message.getWrapperField(this, proto.teleport.terminal.v1.ResourceAccess, 1));
};


/**
 * @param {?proto.teleport.terminal.v1.ResourceAccess|undefined} value
 * @return {!proto.teleport.terminal.v1.ClusterACL} returns this
*/
proto.teleport.terminal.v1.ClusterACL.prototype.setSessions = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.teleport.terminal.v1.ClusterACL} returns this
 */
proto.teleport.terminal.v1.ClusterACL.prototype.clearSessions = function() {
  return this.setSessions(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.teleport.terminal.v1.ClusterACL.prototype.hasSessions = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ResourceAccess auth_connectors = 2;
 * @return {?proto.teleport.terminal.v1.ResourceAccess}
 */
proto.teleport.terminal.v1.ClusterACL.prototype.getAuthConnectors = function() {
  return /** @type{?proto.teleport.terminal.v1.ResourceAccess} */ (
    jspb.Message.getWrapperField(this, proto.teleport.terminal.v1.ResourceAccess, 2));
};


/**
 * @param {?proto.teleport.terminal.v1.ResourceAccess|undefined} value
 * @return {!proto.teleport.terminal.v1.ClusterACL} returns this
*/
proto.teleport.terminal.v1.ClusterACL.prototype.setAuthConnectors = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.teleport.terminal.v1.ClusterACL} returns this
 */
proto.teleport.terminal.v1.ClusterACL.prototype.clearAuthConnectors = function() {
  return this.setAuthConnectors(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.teleport.terminal.v1.ClusterACL.prototype.hasAuthConnectors = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional ResourceAccess roles = 3;
 * @return {?proto.teleport.terminal.v1.ResourceAccess}
 */
proto.teleport.terminal.v1.ClusterACL.prototype.getRoles = function() {
  return /** @type{?proto.teleport.terminal.v1.ResourceAccess} */ (
    jspb.Message.getWrapperField(this, proto.teleport.terminal.v1.ResourceAccess, 3));
};


/**
 * @param {?proto.teleport.terminal.v1.ResourceAccess|undefined} value
 * @return {!proto.teleport.terminal.v1.ClusterACL} returns this
*/
proto.teleport.terminal.v1.ClusterACL.prototype.setRoles = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.teleport.terminal.v1.ClusterACL} returns this
 */
proto.teleport.terminal.v1.ClusterACL.prototype.clearRoles = function() {
  return this.setRoles(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.teleport.terminal.v1.ClusterACL.prototype.hasRoles = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional ResourceAccess users = 4;
 * @return {?proto.teleport.terminal.v1.ResourceAccess}
 */
proto.teleport.terminal.v1.ClusterACL.prototype.getUsers = function() {
  return /** @type{?proto.teleport.terminal.v1.ResourceAccess} */ (
    jspb.Message.getWrapperField(this, proto.teleport.terminal.v1.ResourceAccess, 4));
};


/**
 * @param {?proto.teleport.terminal.v1.ResourceAccess|undefined} value
 * @return {!proto.teleport.terminal.v1.ClusterACL} returns this
*/
proto.teleport.terminal.v1.ClusterACL.prototype.setUsers = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.teleport.terminal.v1.ClusterACL} returns this
 */
proto.teleport.terminal.v1.ClusterACL.prototype.clearUsers = function() {
  return this.setUsers(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.teleport.terminal.v1.ClusterACL.prototype.hasUsers = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional ResourceAccess trusted_clusters = 5;
 * @return {?proto.teleport.terminal.v1.ResourceAccess}
 */
proto.teleport.terminal.v1.ClusterACL.prototype.getTrustedClusters = function() {
  return /** @type{?proto.teleport.terminal.v1.ResourceAccess} */ (
    jspb.Message.getWrapperField(this, proto.teleport.terminal.v1.ResourceAccess, 5));
};


/**
 * @param {?proto.teleport.terminal.v1.ResourceAccess|undefined} value
 * @return {!proto.teleport.terminal.v1.ClusterACL} returns this
*/
proto.teleport.terminal.v1.ClusterACL.prototype.setTrustedClusters = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.teleport.terminal.v1.ClusterACL} returns this
 */
proto.teleport.terminal.v1.ClusterACL.prototype.clearTrustedClusters = function() {
  return this.setTrustedClusters(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.teleport.terminal.v1.ClusterACL.prototype.hasTrustedClusters = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional ResourceAccess events = 6;
 * @return {?proto.teleport.terminal.v1.ResourceAccess}
 */
proto.teleport.terminal.v1.ClusterACL.prototype.getEvents = function() {
  return /** @type{?proto.teleport.terminal.v1.ResourceAccess} */ (
    jspb.Message.getWrapperField(this, proto.teleport.terminal.v1.ResourceAccess, 6));
};


/**
 * @param {?proto.teleport.terminal.v1.ResourceAccess|undefined} value
 * @return {!proto.teleport.terminal.v1.ClusterACL} returns this
*/
proto.teleport.terminal.v1.ClusterACL.prototype.setEvents = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.teleport.terminal.v1.ClusterACL} returns this
 */
proto.teleport.terminal.v1.ClusterACL.prototype.clearEvents = function() {
  return this.setEvents(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.teleport.terminal.v1.ClusterACL.prototype.hasEvents = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional ResourceAccess tokens = 7;
 * @return {?proto.teleport.terminal.v1.ResourceAccess}
 */
proto.teleport.terminal.v1.ClusterACL.prototype.getTokens = function() {
  return /** @type{?proto.teleport.terminal.v1.ResourceAccess} */ (
    jspb.Message.getWrapperField(this, proto.teleport.terminal.v1.ResourceAccess, 7));
};


/**
 * @param {?proto.teleport.terminal.v1.ResourceAccess|undefined} value
 * @return {!proto.teleport.terminal.v1.ClusterACL} returns this
*/
proto.teleport.terminal.v1.ClusterACL.prototype.setTokens = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.teleport.terminal.v1.ClusterACL} returns this
 */
proto.teleport.terminal.v1.ClusterACL.prototype.clearTokens = function() {
  return this.setTokens(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.teleport.terminal.v1.ClusterACL.prototype.hasTokens = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional ResourceAccess servers = 8;
 * @return {?proto.teleport.terminal.v1.ResourceAccess}
 */
proto.teleport.terminal.v1.ClusterACL.prototype.getServers = function() {
  return /** @type{?proto.teleport.terminal.v1.ResourceAccess} */ (
    jspb.Message.getWrapperField(this, proto.teleport.terminal.v1.ResourceAccess, 8));
};


/**
 * @param {?proto.teleport.terminal.v1.ResourceAccess|undefined} value
 * @return {!proto.teleport.terminal.v1.ClusterACL} returns this
*/
proto.teleport.terminal.v1.ClusterACL.prototype.setServers = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.teleport.terminal.v1.ClusterACL} returns this
 */
proto.teleport.terminal.v1.ClusterACL.prototype.clearServers = function() {
  return this.setServers(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.teleport.terminal.v1.ClusterACL.prototype.hasServers = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional ResourceAccess apps = 9;
 * @return {?proto.teleport.terminal.v1.ResourceAccess}
 */
proto.teleport.terminal.v1.ClusterACL.prototype.getApps = function() {
  return /** @type{?proto.teleport.terminal.v1.ResourceAccess} */ (
    jspb.Message.getWrapperField(this, proto.teleport.terminal.v1.ResourceAccess, 9));
};


/**
 * @param {?proto.teleport.terminal.v1.ResourceAccess|undefined} value
 * @return {!proto.teleport.terminal.v1.ClusterACL} returns this
*/
proto.teleport.terminal.v1.ClusterACL.prototype.setApps = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.teleport.terminal.v1.ClusterACL} returns this
 */
proto.teleport.terminal.v1.ClusterACL.prototype.clearApps = function() {
  return this.setApps(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.teleport.terminal.v1.ClusterACL.prototype.hasApps = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional ResourceAccess dbs = 10;
 * @return {?proto.teleport.terminal.v1.ResourceAccess}
 */
proto.teleport.terminal.v1.ClusterACL.prototype.getDbs = function() {
  return /** @type{?proto.teleport.terminal.v1.ResourceAccess} */ (
    jspb.Message.getWrapperField(this, proto.teleport.terminal.v1.ResourceAccess, 10));
};


/**
 * @param {?proto.teleport.terminal.v1.ResourceAccess|undefined} value
 * @return {!proto.teleport.terminal.v1.ClusterACL} returns this
*/
proto.teleport.terminal.v1.ClusterACL.prototype.setDbs = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.teleport.terminal.v1.ClusterACL} returns this
 */
proto.teleport.terminal.v1.ClusterACL.prototype.clearDbs = function() {
  return this.setDbs(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.teleport.terminal.v1.ClusterACL.prototype.hasDbs = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional ResourceAccess kubeservers = 11;
 * @return {?proto.teleport.terminal.v1.ResourceAccess}
 */
proto.teleport.terminal.v1.ClusterACL.prototype.getKubeservers = function() {
  return /** @type{?proto.teleport.terminal.v1.ResourceAccess} */ (
    jspb.Message.getWrapperField(this, proto.teleport.terminal.v1.ResourceAccess, 11));
};


/**
 * @param {?proto.teleport.terminal.v1.ResourceAccess|undefined} value
 * @return {!proto.teleport.terminal.v1.ClusterACL} returns this
*/
proto.teleport.terminal.v1.ClusterACL.prototype.setKubeservers = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.teleport.terminal.v1.ClusterACL} returns this
 */
proto.teleport.terminal.v1.ClusterACL.prototype.clearKubeservers = function() {
  return this.setKubeservers(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.teleport.terminal.v1.ClusterACL.prototype.hasKubeservers = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * repeated string ssh_logins = 12;
 * @return {!Array<string>}
 */
proto.teleport.terminal.v1.ClusterACL.prototype.getSshLoginsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 12));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.teleport.terminal.v1.ClusterACL} returns this
 */
proto.teleport.terminal.v1.ClusterACL.prototype.setSshLoginsList = function(value) {
  return jspb.Message.setField(this, 12, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.teleport.terminal.v1.ClusterACL} returns this
 */
proto.teleport.terminal.v1.ClusterACL.prototype.addSshLogins = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 12, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.teleport.terminal.v1.ClusterACL} returns this
 */
proto.teleport.terminal.v1.ClusterACL.prototype.clearSshLoginsList = function() {
  return this.setSshLoginsList([]);
};


/**
 * optional ResourceAccess access_requests = 13;
 * @return {?proto.teleport.terminal.v1.ResourceAccess}
 */
proto.teleport.terminal.v1.ClusterACL.prototype.getAccessRequests = function() {
  return /** @type{?proto.teleport.terminal.v1.ResourceAccess} */ (
    jspb.Message.getWrapperField(this, proto.teleport.terminal.v1.ResourceAccess, 13));
};


/**
 * @param {?proto.teleport.terminal.v1.ResourceAccess|undefined} value
 * @return {!proto.teleport.terminal.v1.ClusterACL} returns this
*/
proto.teleport.terminal.v1.ClusterACL.prototype.setAccessRequests = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.teleport.terminal.v1.ClusterACL} returns this
 */
proto.teleport.terminal.v1.ClusterACL.prototype.clearAccessRequests = function() {
  return this.setAccessRequests(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.teleport.terminal.v1.ClusterACL.prototype.hasAccessRequests = function() {
  return jspb.Message.getField(this, 13) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.teleport.terminal.v1.ResourceAccess.prototype.toObject = function(opt_includeInstance) {
  return proto.teleport.terminal.v1.ResourceAccess.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.teleport.terminal.v1.ResourceAccess} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.teleport.terminal.v1.ResourceAccess.toObject = function(includeInstance, msg) {
  var f, obj = {
    list: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    read: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    edit: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    create: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    pb_delete: jspb.Message.getBooleanFieldWithDefault(msg, 5, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.teleport.terminal.v1.ResourceAccess}
 */
proto.teleport.terminal.v1.ResourceAccess.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.teleport.terminal.v1.ResourceAccess;
  return proto.teleport.terminal.v1.ResourceAccess.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.teleport.terminal.v1.ResourceAccess} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.teleport.terminal.v1.ResourceAccess}
 */
proto.teleport.terminal.v1.ResourceAccess.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setList(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRead(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEdit(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCreate(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDelete(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.teleport.terminal.v1.ResourceAccess.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.teleport.terminal.v1.ResourceAccess.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.teleport.terminal.v1.ResourceAccess} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.teleport.terminal.v1.ResourceAccess.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getList();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getRead();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getEdit();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getCreate();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getDelete();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
};


/**
 * optional bool list = 1;
 * @return {boolean}
 */
proto.teleport.terminal.v1.ResourceAccess.prototype.getList = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.teleport.terminal.v1.ResourceAccess} returns this
 */
proto.teleport.terminal.v1.ResourceAccess.prototype.setList = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional bool read = 2;
 * @return {boolean}
 */
proto.teleport.terminal.v1.ResourceAccess.prototype.getRead = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.teleport.terminal.v1.ResourceAccess} returns this
 */
proto.teleport.terminal.v1.ResourceAccess.prototype.setRead = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool edit = 3;
 * @return {boolean}
 */
proto.teleport.terminal.v1.ResourceAccess.prototype.getEdit = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.teleport.terminal.v1.ResourceAccess} returns this
 */
proto.teleport.terminal.v1.ResourceAccess.prototype.setEdit = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool create = 4;
 * @return {boolean}
 */
proto.teleport.terminal.v1.ResourceAccess.prototype.getCreate = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.teleport.terminal.v1.ResourceAccess} returns this
 */
proto.teleport.terminal.v1.ResourceAccess.prototype.setCreate = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional bool delete = 5;
 * @return {boolean}
 */
proto.teleport.terminal.v1.ResourceAccess.prototype.getDelete = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.teleport.terminal.v1.ResourceAccess} returns this
 */
proto.teleport.terminal.v1.ResourceAccess.prototype.setDelete = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


goog.object.extend(exports, proto.teleport.terminal.v1);
