availableSecrets:
  secretManager:
  - versionName: projects/771512790633/secrets/webassets-e-deployment-key/versions/2
    env: WEBASSETS_DEPLOYMENT_KEY

steps:
  - name: golang:1.17
    id: checkout
    secretEnv:
      - WEBASSETS_DEPLOYMENT_KEY
    entrypoint: /bin/bash
    dir: .cloudbuild/scripts
    args:
      - "-c"
      - "go run ./cmd/checkout -w=/workspace"

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--build-arg'
      - NPM_SCRIPT=test
      - .
