availableSecrets:
  secretManager:
  - versionName: projects/771512790633/secrets/webapps-e-deployment-key/versions/1
    env: WEBAPPS_E_DEPLOYMENT_KEY

steps:
  - name: golang:1.17
    id: checkout
    secretEnv:
      - WEBAPPS_E_DEPLOYMENT_KEY
    entrypoint: /bin/bash
    dir: .cloudbuild/scripts
    args:
      - "-c"
      - "go run ./cmd/checkout -w=/workspace"

  - name: gcr.io/cloud-builders/docker
    id: type-check
    args:
      - build
      - '--build-arg'
      - NPM_SCRIPT=type-check
      - '--build-arg'
      - YARN_FROZEN_LOCKFILE=true
      - .

  - name: gcr.io/cloud-builders/docker
    id: test
    args:
      - build
      - '--build-arg'
      - NPM_SCRIPT=test
      - '--build-arg'
      - YARN_FROZEN_LOCKFILE=true
      - .
