name: Update Webassets

on:
  push:
    branches:
      - master
      # TODO(zmb3): enable on release branches
      #- teleport-v**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Get webapps, and the webapps.e submodule
      - name: Checkout webapps
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          submodules: recursive
          fetch-depth: 0

      # Get webassets, and the webassets.e submodule
      - name: Checkout webassets
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          repository: gravitational/webassets-fork # TODO(zmb3): switch off the fork
          submodules: recursive
          path: dist

      # This workflow only runs on push to a protected branch, so the code
      # has already been reviewed and is trusted. This means it is safe to
      # the version of the action that we checked out and we don't need to
      # always use master.
      - name: Build webassets
        uses: ./.github/actions/docker-build-webassets

      - name: Push updates
        run: |
          git config --global user.email github-goteleport-core-svc@goteleport.com
          git config --global user.name "$GITHUB_ACTOR"

          export WEBAPPS_BRANCH=$(git branch --show-current)

          cd dist/e
          git switch $WEBAPPS_BRANCH
          git add -A
          git commit -m "Update webassets.e from gravitational/webapps@$GITHUB_SHA"
          git push

          cd ..
          git switch $WEBAPPS_BRANCH
          git add -A
          git commit -m "Update webassets from gravitational/webapps@$GITHUB_SHA"
          git push
